### ISSUE TITLE
Not working for me...

### ISSUE THREAD

**Issue by faiizow** [jerwuqu/osunp#1]
```javascript
var osunp = require('osunp')

osunp.start(function (data) {
  console.dir(data)
})

process.on('exit', function (){
  osunp.stop()
});
```

This code on Node v6.0.0 doesn't work. Any ideas why?

**Comment by jerwuqu** [comment]
That's weird. I just tested it myself in v6.0.0 and it worked. 

Did you enable MSN Live integration in osu?

**Comment by faiizow** [comment]
Yeah. Is this supposed to work with the stable build of osu! or the bleeding edge?

**Comment by jerwuqu** [comment]
I myself am running cutting-edge but the MSN integration has existed for years and hasn't really changed so it shouldn't be any different.

Which version of Windows are your running?

**Comment by faiizow** [comment]
Windows 10.

**Comment by jerwuqu** [comment]
That's the same as me then. Unless something went wrong during compilation, I really have no idea.

Have you tried any other applications that use the MSN Live integration?

**Comment by faiizow** [comment]
This works for me now, it was something to do with me using Command Prompt (Admin) and not the regular privileged one.. :/ Thanks for your time though. :) <3 <3

**Comment by jerwuqu** [comment]
Great! :D
